dp/filexp/filexp/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    
    url(r'^search/', include('search.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

dp/filexp/search/urls.py
from django.conf.urls import patterns , url
from search import views
urlpatterns = patterns( '',
       url(r'^$' , views.index , name='index'),
       url(r'^misearch/$', views.misearch, name='misearch'),
       url(r'^(?P<pk>\d+)/exd/$', views.exd,name='detail'),
       
       
)

dp/filexp/search/models.py
from django.db import models
from login.models import UserProfile
import datetime
class Page(models.Model):
     profile = models.ManyToManyField(UserProfile)
     title = models.CharField(max_length=100)
     url = models.URLField(max_length=200)
     datetime = models.DateTimeField('date_publish')
     def __str__(self):              
        return self.title
     
     

class Expression(models.Model):
      page = models.ForeignKey(Page)
      exp_text = models.CharField(max_length=50,blank=True)
      rating = models.IntegerField(default=0)
      def __str__(self):             
        return self.exp_text

dp/filexp/search/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from search.models import Page,Expression 
def index(request):
    sr=Page.objects.get(pk=10)
    return render(request,'search/index.html', {'sr':sr})
def misearch(request):
    if request.method == 'POST':
        search = request.POST['search']
    sr=Page.objects.filter(expression__exp_text__icontains=search)
    
    return render(request,'search/misearch.html', {'sr':sr})

def exd(request , pk):
    detail=Expression.objects.get(id=pk)
    detail.rating +=1
    detail.save()
    return HttpResponseRedirect('/search/')

dp/filexp/templates/search/dtail.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
    <title> MiReder </title> 
   <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
  </head>

   <body class="body">
     <div class="header">

     <h1> MiReder </h1>
     </div> 
     <div align="center"> 
        
          {{detail}}   <br>

     </div>
   </body>
</html>
         

dp/filexp/templates/search/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
    <title> MiReder </title> 
   <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
  </head>

   <body class="body">
     <div class="header">

     <h1> MiReder </h1>
     </div>  
    <div id="first">
      
        <form  method="post" action="/search/misearch/">
            {% csrf_token %}
             <input type="text" name="search" value="" size="20" />
            

             <input type="submit" value="search" />
        </form>
      
     </div>
  
   </body>
</html>
         

dp/filexp/templates/search/misearch.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
    <title> MiReder </title> 
   <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
  </head>

   <body class="body">
     <div class="header">

     <h1> MiReder </h1>
     </div> 
     <div align="center"> 
      {%for k in sr%}
        <h1><a href="{{k.url}}">{{k.title}}</a></h1><br />
          {%for i in k.expression_set.all%}
              <a href="{% url 'detail' i.id %}">{{i.exp_text}}</a> <h> ({{i.rating}})</h><br />
          {%endfor%}
      {%endfor%}
     </div>
   </body>
</html>